/// Lightweight wrapper around `flutter_local_notifications` for the
/// trip-lifecycle banners (auto-start, auto-stop). The intrusive
/// foreground-service notification that Android shows while tracking is
/// generated by Tracelet itself — these are *informational* nudges on top.
library;

import 'dart:io';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'app_logger.dart';

class AppNotifications {
  static final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();
  static const _channelId = 'trip_lifecycle';
  static const _channelName = 'Jazda';
  static const _channelDesc = 'Notifikácie pri začiatku a ukončení jazdy';
  // Avoid IDs Tracelet's foreground-service notification might be using
  // (it tends to claim small integer IDs).
  static const _tripNotifId = 1001;
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    // Notification small-icons must be alpha-only silhouettes; Android colours
    // them with the system tint. ic_stat_notify is rendered from the
    // transparent autologic_icon master into per-density drawable folders.
    const settings = InitializationSettings(
      android: AndroidInitializationSettings('ic_stat_notify'),
    );
    await _plugin.initialize(settings);
    if (Platform.isAndroid) {
      const channel = AndroidNotificationChannel(
        _channelId,
        _channelName,
        description: _channelDesc,
        importance: Importance.defaultImportance,
      );
      final android = _plugin
          .resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>();
      await android?.createNotificationChannel(channel);
      // Android 13+ refuses to surface notifications without runtime
      // permission. The onboarding wizard handles this for new installs;
      // cover skip-onboarding (or first launch) here as a backstop.
      final enabled = await android?.areNotificationsEnabled() ?? false;
      if (!enabled) {
        final granted = await android?.requestNotificationsPermission();
        AppLogger.info('Notification permission requested at init: $granted');
      }
    }
    _initialized = true;
  }

  static Future<bool> _ensureNotificationsAllowed() async {
    if (!Platform.isAndroid) return true;
    final android = _plugin.resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin>();
    final enabled = await android?.areNotificationsEnabled() ?? false;
    if (!enabled) {
      AppLogger.warn(
        'Notifications are disabled by the OS — trip banner will not surface',
      );
    }
    return enabled;
  }

  static Future<void> showTripStarted({String? vehicleLabel}) async {
    try {
      await init();
      if (!await _ensureNotificationsAllowed()) return;
      await _plugin.show(
        _tripNotifId,
        'Jazda začala',
        vehicleLabel != null && vehicleLabel.isNotEmpty
            ? '$vehicleLabel — sledovanie polohy aktívne'
            : 'Sledovanie polohy aktívne',
        const NotificationDetails(
          android: AndroidNotificationDetails(
            _channelId,
            _channelName,
            channelDescription: _channelDesc,
            importance: Importance.defaultImportance,
            priority: Priority.defaultPriority,
            ongoing: false,
            autoCancel: true,
          ),
        ),
      );
    } catch (error) {
      AppLogger.warn('Trip-start notification failed: $error');
    }
  }

  static Future<void> showTripStopped({
    String? vehicleLabel,
    Duration? duration,
  }) async {
    try {
      await init();
      if (!await _ensureNotificationsAllowed()) return;
      final parts = <String>[];
      if (vehicleLabel != null && vehicleLabel.isNotEmpty) parts.add(vehicleLabel);
      if (duration != null) parts.add(_formatDuration(duration));
      final body = parts.isEmpty ? 'Sledovanie ukončené' : parts.join(' · ');
      await _plugin.show(
        _tripNotifId,
        'Jazda ukončená',
        body,
        const NotificationDetails(
          android: AndroidNotificationDetails(
            _channelId,
            _channelName,
            channelDescription: _channelDesc,
            importance: Importance.defaultImportance,
            priority: Priority.defaultPriority,
            ongoing: false,
            autoCancel: true,
          ),
        ),
      );
    } catch (error) {
      AppLogger.warn('Trip-stop notification failed: $error');
    }
  }

  static String _formatDuration(Duration d) {
    final h = d.inHours;
    final m = d.inMinutes.remainder(60);
    if (h > 0) return '$h h ${m.toString().padLeft(2, '0')} min';
    return '$m min';
  }
}
