/// Lightweight wrapper around `flutter_local_notifications` for the
/// trip-lifecycle banners (auto-start, auto-stop). The intrusive
/// foreground-service notification that Android shows while tracking is
/// generated by Tracelet itself — these are *informational* nudges on top.
library;

import 'dart:io';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'app_logger.dart';

class AppNotifications {
  static final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();
  static const _channelId = 'trip_lifecycle';
  static const _channelName = 'Jazda';
  static const _channelDesc = 'Notifikácie pri začiatku a ukončení jazdy';
  static const _tripNotifId = 1;
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    const settings = InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
    );
    await _plugin.initialize(settings);
    if (Platform.isAndroid) {
      const channel = AndroidNotificationChannel(
        _channelId,
        _channelName,
        description: _channelDesc,
        importance: Importance.defaultImportance,
      );
      await _plugin
          .resolvePlatformSpecificImplementation<
              AndroidFlutterLocalNotificationsPlugin>()
          ?.createNotificationChannel(channel);
    }
    _initialized = true;
  }

  static Future<void> showTripStarted({String? vehicleLabel}) async {
    try {
      await init();
      await _plugin.show(
        _tripNotifId,
        'Jazda začala',
        vehicleLabel != null && vehicleLabel.isNotEmpty
            ? '$vehicleLabel — sledovanie polohy aktívne'
            : 'Sledovanie polohy aktívne',
        const NotificationDetails(
          android: AndroidNotificationDetails(
            _channelId,
            _channelName,
            channelDescription: _channelDesc,
            importance: Importance.defaultImportance,
            priority: Priority.defaultPriority,
            ongoing: false,
            autoCancel: true,
          ),
        ),
      );
    } catch (error) {
      AppLogger.warn('Trip-start notification failed: $error');
    }
  }

  static Future<void> showTripStopped({
    String? vehicleLabel,
    Duration? duration,
  }) async {
    try {
      await init();
      final parts = <String>[];
      if (vehicleLabel != null && vehicleLabel.isNotEmpty) parts.add(vehicleLabel);
      if (duration != null) parts.add(_formatDuration(duration));
      final body = parts.isEmpty ? 'Sledovanie ukončené' : parts.join(' · ');
      await _plugin.show(
        _tripNotifId,
        'Jazda ukončená',
        body,
        const NotificationDetails(
          android: AndroidNotificationDetails(
            _channelId,
            _channelName,
            channelDescription: _channelDesc,
            importance: Importance.defaultImportance,
            priority: Priority.defaultPriority,
            ongoing: false,
            autoCancel: true,
          ),
        ),
      );
    } catch (error) {
      AppLogger.warn('Trip-stop notification failed: $error');
    }
  }

  static String _formatDuration(Duration d) {
    final h = d.inHours;
    final m = d.inMinutes.remainder(60);
    if (h > 0) return '$h h ${m.toString().padLeft(2, '0')} min';
    return '$m min';
  }
}
